sudo: required
services:
    - docker

before_install:
    - ls
    - docker build -t levonsargsyan1990/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true levonsargsyan1990/react-test npm test

after_success:
    - docker build -t levonsargsyan1990/multi-nginx ./nginx
    - docker build -t levonsargsyan1990/multi-client ./client
    - docker build -t levonsargsyan1990/multi-server ./server
    - docker build -t levonsargsyan1990/multi-worker ./worker
    - docker login -u ${DOCKER_ID} -p ${DOCKER_PASSWORD}
    - docker push levonsargsyan1990/multi-nginx
    - docker push levonsargsyan1990/multi-client
    - docker push levonsargsyan1990/multi-server
    - docker push levonsargsyan1990/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-503240970161
    bucket_path: docket-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

